# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UniVent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UniVent

  target 'UniVentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UniVentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Pods for Facebook

pod ‘FBSDKCoreKit’
pod ‘FBSDKShareKit’
pod ‘FBSDKLoginKit’
pod ‘Eureka’
pod ’GoogleMaps’
pod ’GooglePlaces’
pod 'SwiftLocation', '3.0.1-beta'

end


